### ISSUE TITLE
Please add links to original font files

### ISSUE THREAD

**Issue by hrgell** [jimstorch/DGGen#35]
Please include information about where you got the font files from and/or if you recompiled them.

**Comment by brunns** [comment]
> Please include information about where you got the font files from and/or if you recompiled them.

From https://fonts.google.com/specimen/Special+Elite I imagine?

**Comment by hrgell** [comment]
> From https://fonts.google.com/specimen/Special+Elite I imagine?

I'd prefer facts rather than speculation and that both of the fonts used are sourced.

**Comment by jimstorch** [comment]
Both fonts purport to open licensing.  Closing.
