### ISSUE TITLE
Criminal has only 3 bond, while Agents Handbook says 4

### ISSUE THREAD

**Issue by arnoid** [jimstorch/DGGen#5]
In generator.py file lines 225 and 226 https://github.com/jimstorch/DGGen/blob/5b417ac3c22e5a15d81ea8ab11997b964fbc6f26/generator.py#L225
https://github.com/jimstorch/DGGen/blob/5b417ac3c22e5a15d81ea8ab11997b964fbc6f26/generator.py#L226

I think there's a typo - one of the bonds should be labelled as `bond4`

**Comment by jimstorch** [comment]
Good catch.  Thank you.  It's fixed now.
